name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Remove tracked PDFs before pushing
      - name: Remove PDFs from repo
        run: |
          echo "*.pdf" >> .gitignore
          git rm --cached -f *.pdf || echo "No PDFs to remove"
          git add .gitignore
          git commit -m "Ignore and remove PDFs" || echo "Nothing to commit"

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://ritijindal30:$HF_TOKEN@huggingface.co/spaces/ritijindal30/Conversational_RAG_with_PDFs_Upload_and_chat_history main
